### ISSUE TITLE
generate sub command needs better validation

### ISSUE THREAD

**Issue by jasonkuhrt** [apollographql/apollo-cli#431]
```
❯ yarn apollo-codegen generate --target typescript-modern --output schema.ts
yarn run v1.7.0
$ /Users/jasonkuhrt/projects/personal/foobar/node_modules/.bin/apollo-codegen generate --target typescript-modern --output schema.ts
TypeError: Cannot read property 'length' of undefined
    at Object.yargs.command.command.command.argv [as handler] (/Users/jasonkuhrt/projects/personal/foobar/node_modules/apollo-codegen/src/cli.js:186:17)
    at Object.runCommand (/Users/jasonkuhrt/projects/personal/foobar/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/jasonkuhrt/projects/personal/foobar/node_modules/yargs/yargs.js:1013:30)
    at Object.get [as argv] (/Users/jasonkuhrt/projects/personal/foobar/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/jasonkuhrt/projects/personal/foobar/node_modules/apollo-codegen/lib/cli.js:197:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

```
❯ yarn apollo-codegen --version
yarn run v1.7.0
$ /Users/jasonkuhrt/projects/personal/foobar/node_modules/.bin/apollo-codegen --version
0.19.1
```

**Comment by jmporchet** [comment]
The argument after generate is the source file/directory, for example `apollo-codegen generate **/*.tsx --target typescript-modern --output schema.ts`

**Comment by jasonkuhrt** [comment]
@jmporchet thanks, yup, should update the issue with “needs better validation” I think.

**Comment by shadaj** [comment]
Missing queries/output now result in nicer errors with the Apollo CLI!
