### ISSUE TITLE
[BUG] apollo-codegen v. 0.20.1 TypeError: Object.values is not a function

### ISSUE THREAD

**Issue by ifbarrera** [apollographql/apollo-cli#454]
`apollo-codegen` version: 0.20.1
`node` version: v6.14.2
`npm` version: 6.1.0

Command: `apollo-codegen generate ./User.graphql --schema schema.json --output API.swift`

Error in Xcode (run through build phase):

![image](https://user-images.githubusercontent.com/3156796/42045889-a5c944ae-7aca-11e8-9ecf-63fe4c4ab19f.png)

And in the console:

```
$ apollo-codegen generate ./User.graphql --schema schema.json --output API.swift
TypeError: Object.values is not a function
    at generator.namespaceDeclaration (/usr/local/lib/node_modules/apollo-codegen/node_modules/apollo-codegen-swift/src/codeGeneration.ts:92:14)
    at SwiftAPIGenerator.namespaceDeclaration (/usr/local/lib/node_modules/apollo-codegen/node_modules/apollo-codegen-swift/src/language.ts:88:9)
    at Object.generateSource (/usr/local/lib/node_modules/apollo-codegen/node_modules/apollo-codegen-swift/src/codeGeneration.ts:87:15)
    at Object.generate [as default] (/usr/local/lib/node_modules/apollo-codegen/src/generate.ts:47:23)
    at Object.yargs.command.command.command.argv [as handler] (/usr/local/lib/node_modules/apollo-codegen/src/cli.ts:213:15)
    at Object.runCommand (/usr/local/lib/node_modules/apollo-codegen/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/apollo-codegen/node_modules/yargs/yargs.js:1013:30)
    at Object.get [as argv] (/usr/local/lib/node_modules/apollo-codegen/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/apollo-codegen/lib/cli.js:200:5)
    at Module._compile (module.js:577:32)
```
I originally hit this while going through the apollo-ios installation instructions. Rolling back to `apollo-codegen 0.20.0` fixed the issue.

**Comment by shadaj** [comment]
Can you try with `apollo-codegen` 0.20.2? The 0.20.1 release had publishing issues.

**Comment by shadaj** [comment]
Closing for now because this has likely been fixed as part of the Apollo CLI rewrite. Feel free to ping for a re-open if you are still having this issue with the Apollo CLI!
