### ISSUE TITLE
Apollo iOS Codegen Error

### ISSUE THREAD

**Issue by ChrisBGriffith** [apollographql/apollo-cli#601]
_Also posted here: https://github.com/apollographql/apollo-ios/issues/371_
I'm in the process of updating the Apollo iOS client from 0.9.0 -> 0.9.3. This incorporates the new CLI script and codegen syntax. I have the proper version of the apollo package installed, but these queries and schema that worked fine with 0.9.0 are failing now.

```
Apollo Codegen Step
++ npx --no-install apollo codegen:generate '--queries=./GraphQL/CompanyLoginInfo.graphql
./GraphQL/User.graphql
./GraphQL/CompanyDetails.graphql
./GraphQL/SigninUser.graphql' '--schema= GraphQL/schema.json' GraphQL/GraphAPI.swift
[?25l[16:02:22] Loading Apollo config [started]
[16:02:22] Loading Apollo config [completed]
[16:02:22] Resolving GraphQL document sets and dependencies [started]
[16:02:22] Scanning for GraphQL queries (4 found) [title changed]
[16:02:22] Scanning for GraphQL queries (4 found) [completed]
[16:02:22] Generating query files [started]
[16:02:22] Generating query files with 'swift' target [title changed]
[16:02:22] Generating query files with 'swift' target [failed]
[16:02:22] → Cannot read property 'getQueryType' of undefined
[?25hTypeError: Cannot read property 'getQueryType' of undefined
    at TypeInfo.enter (/usr/local/lib/node_modules/apollo/node_modules/graphql/utilities/TypeInfo.js:142:25)
    at Object.enter (/usr/local/lib/node_modules/apollo/node_modules/graphql/language/visitor.js:363:16)
    at Object.visit (/usr/local/lib/node_modules/apollo/node_modules/graphql/language/visitor.js:254:26)
    at getValidationErrors (/usr/local/lib/node_modules/apollo/lib/validation.js:21:15)
    at Object.validateQueryDocument (/usr/local/lib/node_modules/apollo/lib/validation.js:26:30)
    at Object.generate [as default] (/usr/local/lib/node_modules/apollo/lib/generate.js:19:18)
    at Task.task (/usr/local/lib/node_modules/apollo/lib/commands/codegen/generate.js:98:64)
    at Promise.resolve.then.then.skipped (/usr/local/lib/node_modules/apollo/node_modules/listr/lib/task.js:167:30)
    at <anonymous>
[?25h
```

**Comment by ChrisBGriffith** [comment]
Turns out the issue is that I needed to add the `--passthroughCustomScalars` flag to the codegen step.
